### ISSUE TITLE
Include Docker File & Docker Image

### ISSUE THREAD

**Issue by cybercamphackathon** [sfaci/masc#11]
Include Dockefile to ease the testing of the project.

If the Docker Image also exist in the DockerHub, would be great.

**Comment by sfaci** [comment]
I have create a docker image based on 'wordpress' image I have found in the Docker Hub.
Now I am waiting for the confirmation email from Docker Hub to upload it

**Comment by cybercamphackathon** [comment]
Nice!

**Comment by sfaci** [comment]
A image with wordpress and masc can be now downloaded from Docker Hub at https://hub.docker.com/r/sfaci/masc-wordpress/
