### ISSUE TITLE
error

### ISSUE THREAD

**Issue by sk3lk0** [sfaci/masc#22]
python masc.py -s -t custom -p test/

masc 0.2.2 (http://github.com/sfaci/masc)
Loading dictionaries and signatures. . .
Loading malware signature files |################################| 100%
Loaded 528746 malware signatures
Loading YARA rules . . . |################################| 100%
Some errors while reading yara rules. Some rules were not loaded
Loaded 717 YARA rules
done.
Loading web site . . .
done.
Making a backup . . .
A previous backups exists. Do you want to overwrite it? [y|N] y
Using no_name as backup name
done.
Searching for malware . . .
Scanning your website (ClamAV not found. Using only checksum and YARA rules databases) Traceback (most recent call last):
  File "masc.py", line 98, in <module>
    results = cms.search_malware_signatures()
  File "/wd/CMS.py", line 117, in search_malware_signatures
    if entry.is_plain_text():
  File "/wd/MascEntry.py", line 47, in is_plain_text
    mg = magic.Magic(mime=True)
TypeError: __init__() got an unexpected keyword argument 'mime'

**Comment by sk3lk0** [comment]
import pyclamd

clamav = pyclamd.ClamdAgnostic()

Traceback (most recent call last):
  File "1.py", line 3, in <module>
    clamav = pyclamd.ClamdAgnostic()
  File "/usr/local/lib/python2.7/dist-packages/pyclamd/pyclamd.py", line 817, in ClamdAgnostic
    raise ValueError("could not connect to clamd server either by unix or network socket")
ValueError: could not connect to clamd server either by unix or network socket

**Comment by sfaci** [comment]
Try to execute with Python >= 3. Masc doesn't support Python 2
