### ISSUE TITLE
Installation issue-> pypandoc.convert_file  

### ISSUE THREAD

**Issue by lrodden** [sfaci/masc#23]
Hi, 

I'm trying to install the package onto an ubuntu server and I keep getting this issue -> 

####################
   ERROR: Command errored out with exit status 1:
     command: /home/landon/app/appenv/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-kcj9sfm_/masc/setup.py'"'"'; __file__='"'"'/tmp/pip-install-kcj9sfm_/masc/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-kcj9sfm_/masc/pip-egg-info
         cwd: /tmp/pip-install-kcj9sfm_/masc/
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-kcj9sfm_/masc/setup.py", line 7, in <module>
        readme = pypandoc.convert_file('README.md', 'rst')
      File "/home/landon/app/appenv/lib/python3.6/site-packages/pypandoc/__init__.py", line 135, in convert_file
        raise RuntimeError("source_file is not a valid path")
    RuntimeError: source_file is not a valid path 
#######################

I'm not too sure what the issue is - but it seems to not like the README file. pypandoc doesn't accept the current path for some reason.

**Comment by sfaci** [comment]
Are you trying to install using pip? Can you explain me how do you do it?

**Comment by sfaci** [comment]
@lrodden I hope the #30 issue fixed this problem forever! @ibLeDy is working on it.
