### ISSUE TITLE
Create temporary files in a folder inside user home directory

### ISSUE THREAD

**Issue by sfaci** [sfaci/masc#33]
Currently masc creates some folders when you execute specific options:

- **cache** folder to store clean installations download during execution
- **backups** folder to store your backups 
- **logs** folder to store logs

But these folders should be created at user home. Differents users can have differentes backups, for example. 

I think the best approach is to keep these folders in a **.masc** folder in the user home directory.

**Comment by isaacvv** [comment]
I can work on this.
