### ISSUE TITLE
Misc fixes

### ISSUE THREAD

**Issue by ibLeDy** [sfaci/masc#37]
There are a couple of things that the linter that i use ([Flake8](https://github.com/PyCQA/flake8)) complains about (i excluded the `line too long` ones), these are the ones may be worth fixing: 
- E703 statement ends with a semicolon (**dictionary.py**, line **40**)
- E722 do not use bare 'except' (**cms.py**, lines **43, 93, 124 and 172**)
- E713 test for membership should be 'not in' (**cms.py**, line **286**)

These ones are minor but may also worth fixing:
- W292 no newline at end of file (**print_utils.py**, line **54**)
- W391 blank line at end of file (**drupal.py**, line **40**) _(there are multiple blank lines actually)_
- W391 blank line at end of file (**joomla.py**, line **21**)
- W504 line break after binary operator (**main.py**, lines **52 and 137**)
- W504 line break after binary operator (**wordpress.py**, line **77**)
- E128 continuation line under-indented for visual indent (**main.py**, lines **53 and 138**)
- F841 local variable 'spinner' is assigned to but never used (**main.py**, line **120**)

_Note: W504 and E128 are related to each other_

PD: When solving W504, some flake8 versions could complain about W503, but seems like it's preferable that operators remain aligned.
- [Flake8's W504 explanation](https://www.flake8rules.com/rules/W504.html)
- [PEP8's "Should a Line Break Before or After a Binary Operator?"](https://www.python.org/dev/peps/pep-0008/#should-a-line-break-before-or-after-a-binary-operator)

**Comment by sfaci** [comment]
Let's go!!!

**Comment by dukebody** [comment]
I take it.

**Comment by dukebody** [comment]
FTR
```
$ pip install flake8
$ flake8 --ignore E501
./virustotal_test.py:3:1: F401 'pyclamd' imported but unused
./virustotal_test.py:23:1: W391 blank line at end of file
./masc/wordpress.py:77:96: W504 line break after binary operator
./masc/cms.py:43:13: E722 do not use bare 'except'
./masc/cms.py:93:9: E722 do not use bare 'except'
./masc/cms.py:124:21: E722 do not use bare 'except'
./masc/cms.py:172:9: E722 do not use bare 'except'
./masc/cms.py:286:16: E713 test for membership should be 'not in'
./masc/print_utils.py:54:57: W292 no newline at end of file
./masc/drupal.py:40:1: W391 blank line at end of file
./masc/dictionary.py:40:29: E703 statement ends with a semicolon
./masc/dictionary.py:72:13: F841 local variable 'e' is assigned to but never used
./masc/joomla.py:21:1: W391 blank line at end of file
./masc/main.py:11:1: E402 module level import not at top of file
./masc/main.py:12:1: E402 module level import not at top of file
./masc/main.py:13:1: E402 module level import not at top of file
./masc/main.py:14:1: E402 module level import not at top of file
./masc/main.py:15:1: E402 module level import not at top of file
./masc/main.py:16:1: E402 module level import not at top of file
./masc/main.py:17:1: E402 module level import not at top of file
./masc/main.py:57:88: W504 line break after binary operator
./masc/main.py:58:21: E128 continuation line under-indented for visual indent
./masc/main.py:125:21: F841 local variable 'spinner' is assigned to but never used
./masc/main.py:142:103: W504 line break after binary operator
./masc/main.py:143:25: E128 continuation line under-indented for visual indent
```
